### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by mudrd8mz** [ndunand/moodle-filter_ubicast#1]
https://github.com/ndunand/moodle-filter_ubicast/blob/9e22dbc16d8d1099ea38bdb7194edc281d2fced7/filter.php#L55-L63

For filters, it is generally recommended, if possible, to first execute a quick and cheap substring check to see if a keyword is present in the text. And only if so, only then perform the slower and more expensive regexp.

In this case, something like this injected to the line 59 could help to avoid unnecessary regexps for most filtered strings.

```
        if (strpos($text, 'atto_ubicast') === false) {
            return $text;
        }
```

**Comment by ndunand** [comment]
Thanks for the suggestion, fixed in 469a185934139c324efecab4f3fba6d821a68e92 !
